micronaut:
  application:
    name: cosmonaut_empresa
  server:
    idle-timeout: 60m
    read-idle-timeout: 60m
    write-idle-timeout: 60m
    port: 8082
    #port: ${APLICACION_PUERTO:8082}
    cors:
      enabled: true
  router:
    static-resources:
      swagger:
        paths: classpath:META-INF/swagger
        mapping: /swagger/**
      rapidoc:
        paths: classpath:META-INF/swagger/views/rapidoc
        mapping: /rapidoc/**
      swagger-ui:
        paths: classpath:META-INF/swagger/views/swagger-ui
        mapping: /swagger-ui/**
      redoc:
        paths: classpath:META-INF/swagger/views/redoc
        mapping: /redoc/**
bpm:
  host: https://localhost:9444
  token: /bpm/system/login 
  instance: /bpm/processes
  instance-cliente: /rest/bpm/wle/v1/search/query?condition=idCliente%7C
  instance-tasks: /rest/bpm/wle/v1/process/
  finish-task: /rest/bpm/wle/v1/task/
  user: bawadmin
  pass: b4w4dm1n
